### ISSUE TITLE
If recipe doesnt have docstring error is thrown but doesnt explain why 

### ISSUE THREAD

**Issue by AutomatedTester** [mozilla/active-data-recipes#139]
I created a new recipe `.py` and when I ran it I got an error throw but didnt explain what I did wrong

```bash
(data) davidburns in ~/development/mochivswpt-recipes(ruby-2.6.0) λ adr mochivswpt         
Traceback (most recent call last):
  File "/Users/davidburns/.virtualenvs/data/bin/adr", line 10, in <module>
    sys.exit(main())
  File "/Users/davidburns/.virtualenvs/data/lib/python3.7/site-packages/adr/cli.py", line 227, in main
    result = handler(remainder)
  File "/Users/davidburns/.virtualenvs/data/lib/python3.7/site-packages/adr/cli.py", line 180, in handle_recipe
    data = run_recipe(config.recipe, remainder)
  File "/Users/davidburns/.virtualenvs/data/lib/python3.7/site-packages/adr/recipe.py", line 83, in run_recipe
    doc = get_docstring(recipe, fmt="text")
  File "/Users/davidburns/.virtualenvs/data/lib/python3.7/site-packages/adr/recipe.py", line 117, in get_docstring
    lines = doc.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

**Comment by ahal** [comment]
Thanks for filing! There's a `./doclint` binary that tests for missing
docstrings when running `tox`. But we shouldn't assume that docstrings are
necessary.
